In [3]:
from analyzer import TimerowForAnalise
from meteostat import Point, Daily
import pandas as pd
from datetime import datetime

In [4]:
# Точка,в которой смотрим температуру - в данном случае Париж
paris = Point(48.8566, 2.3522)

# Временной диапазон
start = datetime(2024, 9, 1)
end = datetime(2024, 10, 1)

# Получение данных о погоде
data = Daily(paris, start, end).fetch()

In [5]:
# Преобразуем индексы в столбцы с датами, чтобы избежать предупреждений
data.reset_index(inplace=True)

# 'tavg' - температура
temperature_data = data['tavg'].to_numpy()

# Создаем анализатор
analyzer = TimerowForAnalise(temperature_data)

In [6]:
# Вычисляем скользящее среднее
results_df = analyzer.get_results()

Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 0     23.1
1     21.3
2     20.0
3     19.3
4     15.8
5     16.4
6     18.5
7     16.4
8     16.7
9     15.1
10    14.6
11    11.3
12    11.4
13    11.4
14    12.0
15    14.3
16    15.9
17    18.1
18    19.1
19    16.4
20    17.3
21    16.9
22    15.4
23    14.9
24    14.2
25    16.5
26    13.0
27    10.5
28     9.6
29    14.7
30    13.8
dtype: float64, 'Temperature') {}
Результат:     Temperature
0          23.1
1          21.3
2          20.0
3          19.3
4          15.8
5          16.4
6          18.5
7          16.4
8          16.7
9          15.1
10         14.6
11         11.3
12         11.4
13         11.4
14         12.0
15         14.3
16         15.9
17         18.1
18         19.1
19         16.4
20         17.3
21         16.9
22         15.4
23         14.9
24         14.2
25         16.5
26         13.0
27         10.5
28          9.6
29         14.7
30         13.8
Вызов функции: calculate_moving_average с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {}
Результат: 0           NaN
1           NaN
2     21.466667
3     20.200000
4     18.366667
5     17.166667
6     16.900000
7     17.100000
8     17.200000
9     16.066667
10    15.466667
11    13.666667
12    12.433333
13    11.366667
14    11.600000
15    12.566667
16    14.066667
17    16.100000
18    17.700000
19    17.866667
20    17.600000
21    16.866667
22    16.533333
23    15.733333
24    14.833333
25    15.200000
26    14.566667
27    13.333333
28    11.033333
29    11.600000
30    12.700000
dtype: float64
Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 0           NaN
1           NaN
2     21.466667
3     20.200000
4     18.366667
5     17.166667
6     16.900000
7     17.100000
8     17.200000
9     16.066667
10    15.466667
11    13.666667
12    12.433333
13    11.366667
14    11.600000
15    12.566667
16    14.066667
17    16.100000
18    17.700000
19    17.866667
20    17.600000
21    16.866667
22    16.533333
23    15.733333
24    14.833333
25    15.200000
26    14.566667
27    13.333333
28    11.033333
29    11.600000
30    12.700000
dtype: float64, 'Moving average') {}
Результат:     Moving average
0              NaN
1              NaN
2        21.466667
3        20.200000
4        18.366667
5        17.166667
6        16.900000
7        17.100000
8        17.200000
9        16.066667
10       15.466667
11       13.666667
12       12.433333
13       11.366667
14       11.600000
15       12.566667
16       14.066667
17       16.100000
18       17.700000
19       17.866667
20       17.600000
21       16.866667
22       16.533333
23       15.733333
24       14.833333
25       15.200000
26       14.566667
27       13.333333
28       11.033333
29       11.600000
30       12.700000
Вызов функции: calculate_differential с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {}
Результат: 0     NaN
1    -1.8
2    -1.3
3    -0.7
4    -3.5
5     0.6
6     2.1
7    -2.1
8     0.3
9    -1.6
10   -0.5
11   -3.3
12    0.1
13    0.0
14    0.6
15    2.3
16    1.6
17    2.2
18    1.0
19   -2.7
20    0.9
21   -0.4
22   -1.5
23   -0.5
24   -0.7
25    2.3
26   -3.5
27   -2.5
28   -0.9
29    5.1
30   -0.9
dtype: float64
Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 0     NaN
1    -1.8
2    -1.3
3    -0.7
4    -3.5
5     0.6
6     2.1
7    -2.1
8     0.3
9    -1.6
10   -0.5
11   -3.3
12    0.1
13    0.0
14    0.6
15    2.3
16    1.6
17    2.2
18    1.0
19   -2.7
20    0.9
21   -0.4
22   -1.5
23   -0.5
24   -0.7
25    2.3
26   -3.5
27   -2.5
28   -0.9
29    5.1
30   -0.9
dtype: float64, 'Differential') {}
Результат:     Differential
0            NaN
1           -1.8
2           -1.3
3           -0.7
4           -3.5
5            0.6
6            2.1
7           -2.1
8            0.3
9           -1.6
10          -0.5
11          -3.3
12           0.1
13           0.0
14           0.6
15           2.3
16           1.6
17           2.2
18           1.0
19          -2.7
20           0.9
21          -0.4
22          -1.5
23          -0.5
24          -0.7
25           2.3
26          -3.5
27          -2.5
28          -0.9
29           5.1
30          -0.9
Вызов функции: calculate_autocorrelation с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {}
Результат: 0    0.793288
dtype: float64
Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 0    0.793288
dtype: float64, 'Autocorrelation') {}
Результат:    Autocorrelation
0         0.793288
Вызов функции: find_maxime с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {}
Результат: 6     18.5
8     16.7
18    19.1
20    17.3
25    16.5
29    14.7
dtype: float64
Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 6     18.5
8     16.7
18    19.1
20    17.3
25    16.5
29    14.7
dtype: float64, 'Max') {}
Результат:      Max
6   18.5
8   16.7
18  19.1
20  17.3
25  16.5
29  14.7
Вызов функции: find_minimum с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {}
Результат: 4     15.8
7     16.4
11    11.3
19    16.4
24    14.2
28     9.6
dtype: float64
Вызов функции: save_to_dataframe с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>, 4     15.8
7     16.4
11    11.3
19    16.4
24    14.2
28     9.6
dtype: float64, 'Min') {}
Результат:      Min
4   15.8
7   16.4
11  11.3
19  16.4
24  14.2
28   9.6
Вызов функции: decompose_time_series с аргументами: (<analyzer.functions_for_analysis.functions_module.TimerowForAnalise object at 0x000002698D56C790>,) {'period': 12}
Результат:         Trend  Seasonal  Residual
0         NaN -1.800521       NaN
1         NaN -3.231771       NaN
2         NaN -2.656771       NaN
3         NaN -0.456771       NaN
4         NaN  1.034896       NaN
5         NaN  3.051563       NaN
6   16.887500  2.728646 -1.116146
7   15.987500  0.614062 -0.201562
8   15.241667  1.459896 -0.001562
9   14.700000  0.789062 -0.389062
10  14.495833  0.101563  0.002604
11  14.570833 -1.633854 -1.636979
12  14.666667 -1.800521 -1.466146
13  14.691667 -3.231771 -0.059896
14  14.716667 -2.656771 -0.059896
15  14.816667 -0.456771 -0.059896
16  14.925000  1.034896 -0.059896
17  15.108333  3.051563 -0.059896
18  15.375000  2.728646  0.996354
19  15.704167  0.614062  0.081771
20  15.958333  1.459896 -0.118229
21  15.841667  0.789062  0.269271
22  15.420833  0.101563 -0.122396
23  15.016667 -1.633854  1.517187
24  14.654167 -1.800521  1.346354
25        NaN -3.231771       NaN
26        NaN -2.656771       NaN
27        NaN -0.456771       NaN
28        NaN  1.034896       NaN
29        NaN  3.051563       NaN
30        NaN  2.728646       NaN

In [7]:
# Объединяем исходные данные и результаты
results_df = pd.concat([data['time'], results_df], axis=1)

In [8]:
# Сохраняем DataFrame в Excel
excel_file = 'results.xlsx'
try:
    with pd.ExcelWriter(excel_file, mode='w', engine='openpyxl') as writer:
        results_df.to_excel(writer, sheet_name='Результаты', index=False)
except FileNotFoundError:
 # Если файл не существует, создаем его
 with pd.ExcelWriter(excel_file, mode='w', engine='openpyxl') as writer:
    results_df.to_excel(writer, sheet_name='Результаты', index=False)

print(f"DataFrame сохранен в файл: {excel_file}")

DataFrame сохранен в файл: results.xlsx